variables:
    # This parameter can be overridden
    TF_VER: '0.12.28'
    # These parameters need to be overridden
    TF_STATE_RESOURCE_GROUP_NAME: ''
    TF_STATE_STORAGE_ACCOUNT_NAME: ''
    TF_STATE_STORAGE_CONTAINER_NAME: ''
    TF_STATE_KEY_NAME: ''
    LOCATION: ''
    ENVIRONMENT:  ''
    BASE_NAME: ''
    ADF_LINK_GITHUB: ''


jobs:
  - job: terraform deployment
    pool:
      vmImage: 'windows-latest'
    steps:
      - pwsh: |
          Invoke-WebRequest -Uri https://releases.hashicorp.com/terraform/$($env:TF_VER)/terraform_$($env:TF_VER)_windows_amd64.zip `
                            -UseBasicParsing -OutFile terraform_$($env:TF_VER)_windows_amd64.zip
          Expand-Archive terraform_$($env:TF_VER)_windows_amd64.zip $(Agent.HomeDirectory)
        displayName: Download Terraform
        
      - pwsh: |
          # Setup Terraform backend
          'resource_group_name  = "$($env:TF_STATE_RESOURCE_GROUP_NAME)"
          storage_account_name  = "$($env:TF_STATE_STORAGE_ACCOUNT_NAME)"
          'container_name  = "$($env:TF_STATE_STORAGE_CONTAINER_NAME)"
          'key  = "$($env:TF_STATE_KEY_NAME)"' | Add-Content -Path 'beconf.tfvars'
          
          # Initialize Terraform
          $(Agent.HomeDirectory)/terraform.exe init -backend-config=beconf.tfvars
        displayName: Terraform Init
        workingDirectory: $(Build.SourcesDirectory)/deploy/terraform

      - pwsh: |
          $(Agent.HomeDirectory)/terraform.exe validate
        displayName: Terraform Validate
        workingDirectory: $(Build.SourcesDirectory)/deploy/terraform

      - pwsh: |
          $(Agent.HomeDirectory)/terraform.exe plan -out plan -no-color -input=false -var location=$($LOCATION) `
                                                    -var environment=$($ENVIRONMENT)  -var base_name=$($BASE_NAME) `
                                                    -var adf_link_github=$($ADF_LINK_GITHUB)
        displayName: Terraform Plan
        workingDirectory: $(Build.SourcesDirectory)/deploy/terraform

      - pwsh: $(Agent.HomeDirectory)/terraform.exe apply plan
        displayName: Terraform Apply
        workingDirectory: $(Build.SourcesDirectory)/deploy/terraform

      